name: vuepress-build-check-deploy

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/vuepress-build-check-deploy.yml
      - docs/**
      - .markdownlint.yml
      - .spelling
      - package.json
      - package-lock.json
  push:
    branches:
      - master
    paths:
      - .github/workflows/vuepress-build-check-deploy.yml
      - docs/**
      - .markdownlint.yml
      - .spelling
      - package.json
      - package-lock.json

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          exclude: |
            CHANGELOG.md

  markdown-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run mdspell
        run: find . -type f \( -name "*.md" ! -name "CHANGELOG.md" \) -print0 | xargs -0 --max-args=1 --verbose mdspell --ignore-numbers --ignore-acronyms --report --en-gb

  # command-check:
  #   name: Command check
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Update repositories
  #       run: sudo apt-get update

  #     - name: Install necessary tools
  #       run: |
  #         sudo apt-get install -y -qq gnupg2 jq pv > /dev/null
  #         curl -s -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  #         curl -s -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/

  #     - name: Run tests
  #       run: |
  #         tests/tests.sh

  vuepress-build-check-deploy:
    runs-on: ubuntu-latest
    needs:
      # - command-check
      - markdownlint-check
      - markdown-spell-check
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install VuePress and build the document
        run: |
          npm install
          npm run build
          cp LICENSE docs/.vuepress/dist
          sed -e "s@(part-@(https://github.com/${{ github.repository }}/tree/master/docs/part-@" -e 's@.\/.vuepress\/public\/@./@' docs/README.md > docs/.vuepress/dist/README.md

      - name: Check broken links
        env:
          INPUT_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          INPUT_PAGES_PATH: .
          INPUT_CMD_PARAMS: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --exclude=(mylabs.dev|ruzickap.github.io/k8s-harbor-presentation)
        run: |
          ln -s docs/.vuepress/dist ${{ github.event.repository.name }}
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v2/entrypoint.sh | bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name }} == 'push' && github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          force_orphan: true
